---
- name: Hide sensitive data using no_log
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Store sensitive information in a variable
      set_fact:
        secret_password: "MySuperSecret123"

    - name: Print secret password (for debugging - will be hidden in logs)
      debug:
        msg: "The password is {{ secret_password }}"
      no_log: true

    - name: Print secret password (for debugging - will be hidden in logs)
      debug:
        msg: "The password is {{ secret_password }}"
